apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    k8s-app: jupyterlab
    notebook-id: {{notebook_id}}
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod-nginx
  name: {{notebook_id}}
  namespace: {{namespace}}
spec:
  rules:
  - host: {{notebook_id}}.{{domain_name}}
    http:
      paths:
      - backend:
          service:
            name: {{notebook_id}}
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - '*.{{domain_name}}'
    secretName: mlnotebook-tls