apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    k8s-app: jupyterlab
    owner: {{owner}}
  name: {{owner}}-cephfs-pvc
  namespace: {{namespace}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs