apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{username}}-cephfs-pvc
  namespace: {{namespace}}
  labels:
    owner: {{username}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: rook-cephfs