apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: jupyterlab
    notebook-id: {{notebook_id}}
  name: {{notebook_id}}
  namespace: {{namespace}}
spec:
  ports:
  - port: 80
    targetPort: 9999
  selector:
    notebook-id: {{notebook_id}}
  type: NodePort